# Generated by Django 5.0.4 on 2024-04-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('season', models.CharField(choices=[('1', '夏定'), ('2', '冬定')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(choices=[('1', '早朝'), ('2', '1限'), ('3', '2限'), ('4', '昼限'), ('5', '3限'), ('6', '4限'), ('7', '5限'), ('8', '6限'), ('9', '夜限')], max_length=10)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(choices=[('1', 'その他/なし'), ('2', '指揮者'), ('3', 'コンサートマスター'), ('4', 'パートリーダー'), ('5', '幹事長'), ('6', '副幹事長'), ('7', '会計')], max_length=20)),
                ('is_staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('generation', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('info1', models.CharField(blank=True, max_length=50, null=True)),
                ('info2', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuragen_app.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room_name', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('1', '音楽練習室(月予約)'), ('2', '音楽練習室(週予約)'), ('3', '音楽練習室(当日予約)'), ('4', '個人ブース'), ('5', '部室'), ('6', 'その他')], max_length=1)),
                ('practice_type', models.CharField(choices=[('1', '合奏練'), ('2', 'パート練'), ('3', 'アンサンブル練'), ('4', 'その他')], max_length=1)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.period')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('updated_time', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.concert')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.song'),
        ),
        migrations.CreateModel(
            name='RideNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=10)),
                ('leader', models.CharField(choices=[('1', '〇'), ('2', '×')], max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuragen_app.song')),
            ],
        ),
    ]
